import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { ResumeProvider } from '@/context/ResumeContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ResumeProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </ResumeProvider>
      </body>
    </html>
  );
}
